POST http://localhost:7071/api/fill-template
content-type: application/json

{
    "data": {
        "Client1FullName": "Awesome Developer",
        "Client1Executor": "Taylor Example"
    },
    "scrub": true,
    "outputName": "filled.vsdx"
}
